(()=>{"use strict";
const $=id=>document.getElementById(id),D=window.RepublicData;
if(!D){document.body.innerHTML='<div style="padding:30px;background:#05060a;color:white">خطای بارگذاری data.js</div>';return}
const S={stage:1,limit:50,screen:"menu",room:"",player:null,players:[],votes:{},current:null,locked:false,queue:[],world:{tension:20,market:50,energy:50,diplomacy:50,inflation:10,mediaNoise:10},fx:true};
const screens=["menu","setup","join","lobby","game","end"];
function show(n){screens.forEach(x=>$(x)?.classList.toggle("active",x===n));S.screen=n;scrollTo(0,0)}
function toast(t){const x=$("toast");x.textContent=t;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2300)}
function loading(v,text="در حال آماده‌سازی..."){$("loading").classList.toggle("show",v);$("loading").querySelector("span").textContent=text}
function fill(id,a){$(id).innerHTML=a.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}
function clamp(v){return Math.max(0,Math.min(100,Number(v)||0))}
function roomCode(){return"ROA"+Math.random().toString(36).slice(2,6).toUpperCase()}
function player(name,cid,gid){const c=D.countries.find(x=>x.id===cid)||D.countries[0],g=D.geographies.find(x=>x.id===gid)||D.geographies[0];let p={id:(crypto.randomUUID?.()||Date.now()+"-"+Math.random()),name,country:c.name,countryId:cid,geoId:gid,money:500,economy:50,energy:50,popularity:50,stability:50,relations:50,sanctions:0,reputation:0,score:0,parliament:50,bureaucracy:50};return apply(p,{...c.effects,...g.effects})}
function apply(p,e){let q={...p};for(const[k,v]of Object.entries(e||{})){if(["tension","market","energyWorld","worldEnergy","diplomacy","inflation","mediaNoise"].includes(k)){const wk=k==="worldEnergy"||k==="energyWorld"?"energy":k;qWorld(wk,Number(v));continue}q[k]=Number(q[k]??0)+Number(v);if(["economy","energy","popularity","stability","relations","sanctions","parliament","bureaucracy"].includes(k))q[k]=clamp(q[k])}return q}
function qWorld(k,v){S.world[k]=Number(S.world[k]??0)+v;if(["tension","market","energy","diplomacy"].includes(k))S.world[k]=clamp(S.world[k])}
function render(){const p=S.player;if(!p)return;for(const k of ["money","economy","energy","popularity","stability","relations","sanctions","score"])$(k).textContent=Math.round(p[k]||0);$("tension").textContent=Math.round(S.world.tension);$("market").textContent=Math.round(S.world.market);$("worldEnergy").textContent=Math.round(S.world.energy);$("diplomacy").textContent=Math.round(S.world.diplomacy);$("stage").textContent=S.stage;$("limit").textContent=S.limit;$("countryName").textContent=p.country;$("leaderName").textContent=p.name}
function renderLobby(){const ps=S.players.length?S.players:[S.player];$("roomTitle").textContent=S.room;$("count").textContent=`${ps.length}/8`;$("players").innerHTML=ps.map((p,i)=>`<div class="player"><span>${i===0?"👑 ":""}${p.name}</span><small>${p.country}</small></div>`).join("");const vals=Object.values(S.votes);const counts=[10,20,30,40,50].map(n=>[n,vals.filter(v=>v===n).length]);const best=counts.sort((a,b)=>b[1]-a[1])[0]?.[0]||50;$("voteStatus").textContent=`رأی فعلی: ${best} مرحله • ${vals.length} رأی`;S.limit=best;document.querySelectorAll("#stages button").forEach(b=>b.classList.toggle("selected",+b.dataset.stage===best))}
function save(){try{localStorage.setItem("ROA_SAVE",JSON.stringify({stage:S.stage,limit:S.limit,player:S.player,world:S.world}))}catch{}}
function chooseStage(n){S.votes[S.player.id]=n;S.limit=n;renderLobby();RepublicRealtime?.send({type:"vote",id:S.player.id,value:n})}
function validEvent(e){return e&&e.title&&Array.isArray(e.choices)&&e.choices.length===3}
async function nextEvent(){S.locked=true;$("director").style.display="flex";$("eventTitle").textContent="مدیر جهان در حال تحلیل...";$("eventDesc").textContent="اقتصاد، افکار عمومی، روابط و تصمیم‌های قبلی در حال بررسی است.";$("choices").innerHTML="";let e=null;if([10,20,30,40,50].includes(S.stage))e=D.specialEvent(S.stage);if(!e&&RepublicAI?.event)e=await RepublicAI.event({stage:S.stage,limit:S.limit,player:S.player,world:S.world,queue:S.queue});if(!validEvent(e))e=D.random();S.current=e;$("director").style.display="none";$("rarity").textContent=e.rarity||"NORMAL";$("eventNo").textContent="EVENT "+String(S.stage).padStart(3,"0");$("eventTitle").textContent=e.title;$("eventDesc").textContent=e.description;$("choices").innerHTML=e.choices.map((c,i)=>`<button class="choice" data-i="${i}"><b>${i+1}. ${escapeHtml(c.title)}</b><span>${escapeHtml(c.text)}</span></button>`).join("");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>decision(+b.dataset.i));$("news").querySelector("span").textContent=D.news[Math.floor(Math.random()*D.news.length)];Office3D?.event?.();S.locked=false}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function decision(i){if(S.locked||!S.current)return;S.locked=true;const cards=[...document.querySelectorAll(".choice")];cards.forEach((c,n)=>{c.classList.toggle("chosen",n===i);c.classList.toggle("rejected",n!==i)});await new Promise(r=>setTimeout(r,420));const choice=S.current.choices[i],before={...S.player};S.player=apply(S.player,choice.effects);S.player.score+=10;S.player.score+=S.player.stability>=65?3:0;const delayed=Math.random()<.28; if(delayed)S.queue.push({stage:S.stage+2,text:"پیامد تأخیری یک تصمیم قدیمی فعال شد.",effects:{stability:-4,popularity:-2}});const due=S.queue.filter(x=>x.stage===S.stage);due.forEach(x=>S.player=apply(S.player,x.effects));S.queue=S.queue.filter(x=>x.stage>S.stage);render();const changes=[];for(const k of ["money","economy","energy","popularity","stability","relations","sanctions","score"]){const d=Math.round((S.player[k]||0)-(before[k]||0));if(d)changes.push(`${k}: ${d>0?"+":""}${d}`)}$("conTitle").textContent=choice.title;$("conText").textContent="تصمیم ثبت شد. جهان به آن واکنش نشان خواهد داد.";$("effects").innerHTML=(changes.length?changes:["بدون تغییر مستقیم"]).map(x=>`<div class="effect-item">${x}</div>`).join("");$("delayBox").textContent=delayed?"⏳ یک پیامد تأخیری در مرحله بعدی ممکن است ظاهر شود.":due.length?"⚠️ یک پیامد تأخیری فعال شد.":"";$("consequence").classList.add("active");save();RepublicRealtime?.send({type:"decision",stage:S.stage,playerId:S.player.id,index:i});}
async function next(){if(!S.player)return;$("consequence").classList.remove("active");if(S.stage>=S.limit){finish();return}S.stage++;render();await nextEvent();RepublicRealtime?.send({type:"stage",stage:S.stage})}
function finish(){const [title,text]=D.ending(S.player.score);$("endTitle").textContent=title;$("endText").textContent=text+` امتیاز نهایی شما ${Math.round(S.player.score)} است.`;$("ranking").innerHTML=`<div class="rank"><b>👑 ${escapeHtml(S.player.name)}</b><span>${Math.round(S.player.score)} امتیاز</span></div>`;$("legacyGrid").innerHTML=[["اقتصاد",S.player.economy],["ثبات",S.player.stability],["محبوبیت",S.player.popularity],["روابط",S.player.relations]].map(x=>`<div><small>${x[0]}</small><b>${Math.round(x[1])}</b></div>`).join("");show("end")}
async function realtime(){if(!window.RepublicRealtime)return;const ok=await RepublicRealtime.connect(S.room,S.player,{message:m=>{if(m.type==="vote"&&m.id!==S.player.id){S.votes[m.id]=m.value;renderLobby()}if(m.type==="stage"&&m.stage>S.stage){S.stage=m.stage;render();nextEvent()}},presence:state=>{const list=Object.values(state||{}).flat();S.players=list.map(x=>x).filter(Boolean);if(!S.players.some(x=>x.id===S.player.id))S.players.push(S.player);renderLobby()}});$("lobbyNote").textContent=ok?"🟢 اتصال آنلاین برقرار است.":"🟡 سرور در دسترس نیست؛ حالت محلی فعال شد."}
function bind(){fill("country",D.countries);fill("joinCountry",D.countries);fill("geo",D.geographies);fill("joinGeo",D.geographies);$("country").onchange=()=>{$("countryPreview").textContent=D.countries.find(x=>x.id===$("country").value)?.desc||""};$("createBtn").onclick=()=>show("setup");$("joinBtn").onclick=()=>show("join");document.querySelectorAll(".back").forEach(b=>b.onclick=()=>show(b.dataset.back));$("confirmSetup").onclick=async()=>{const n=$("leader").value.trim();if(!n)return toast("نام رئیس‌جمهور را وارد کن.");S.room=roomCode();S.player=player(n,$("country").value,$("geo").value);S.players=[S.player];S.votes={[S.player.id]:50};renderLobby();show("lobby");await realtime()};$("confirmJoin").onclick=async()=>{const n=$("joinLeader").value.trim(),r=$("room").value.trim().toUpperCase();if(!n||r.length<4)return toast("کد اتاق و نام را کامل وارد کن.");S.room=r;S.player=player(n,$("joinCountry").value,$("joinGeo").value);S.players=[S.player];S.votes={[S.player.id]:50};renderLobby();show("lobby");await realtime()};document.querySelectorAll("#stages button").forEach(b=>b.onclick=()=>chooseStage(+b.dataset.stage));$("startBtn").onclick=async()=>{show("game");Office3D?.init?.();render();await nextEvent();RepublicRealtime?.send({type:"start",limit:S.limit})};$("nextBtn").onclick=next;$("againBtn").onclick=()=>location.reload();$("copyRoom").onclick=()=>{if(navigator.clipboard)navigator.clipboard.writeText(S.room).then(()=>toast("کد اتاق کپی شد"));else toast(S.room)};$("fxBtn").onclick=()=>{S.fx=!S.fx;$("fxBtn").textContent=S.fx?"🔊":"🔇"}}
window.RepublicGame={version:"12.0-cinematic",state:S,start:()=>show("menu"),chooseDecision:decision,nextStage:next,reset:()=>location.reload(),debug:()=>console.log("ROA_STATE",S)};
window.addEventListener("error",e=>{console.error("ROA:",e.error||e.message);toast("خطای فنی؛ جزئیات در Console Acode ثبت شد.")});
document.addEventListener("DOMContentLoaded",()=>{bind();setTimeout(()=>{$("boot").style.display="none";$("app").classList.remove("hidden")},2100)});
})();